# Generated by Django 5.2.8 on 2026-01-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaddress',
            name='building_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingaddress',
            name='house_no',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingaddress',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingaddress',
            name='city',
            field=models.CharField(default='Bangalore', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingaddress',
            name='state',
            field=models.CharField(default='Karnataka', max_length=100),
        ),
    ]
