# Generated by Django 5.2.6 on 2026-03-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingaddress',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='bookingaddress',
            name='house_no',
        ),
        migrations.AddField(
            model_name='bookingaddress',
            name='coordination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
