# Generated by Django 5.2.6 on 2026-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_remove_bookingaddress_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaddress',
            name='house_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
